---
title: "Publications"
output: html_document

---

***Textbook***

Gilljam, Mikael and Mikael Persson. (2015). [Den allmänna opinionen: En introducerande handbok.](dao.pdf) Stockholm: Liber. (Introductory textbook on public opinion research. If you want a printed copy, e-mail me and I'll send you one for free).

***Selected journal publications***

Persson, Mikael. (Forthcoming). [“Who Got What They Wanted? \\
 Investigating the Role of Institutional Agenda Setting, Costly Policies, and Status Quo Bias as Explanations to Income Based Unequal Responsiveness"](jepp.pdf) *Journal of European Public Policy*.

Persson, Mikael and Anders Sundell (Forthcoming). [“The Rich Have a Slight Edge: Evidence from Comparative Data on Income Based Inequality in Policy Congruence."](bjps23.pdf) *British Journal of Political Science*.

Guntermann, Eric, and Mikael Persson. 2021. [“Issue Voting and Government Responsiveness to Policy Preferences.”](pb21.pdf) *Political Behavior*, 1–24.

Persson, Mikael. 2021. [“From Opinions to Policies: Examining the Links Between Citizens, Representatives, and Policy Change.”](es21.pdf) *Electoral Studies* 74: 102413.

Persson, Mikael, Klas Andersson, Pär Zetterberg, Joakim Ekman, and Simon Lundin. 2020. [“Does Deliberative Education Increase Civic Competence? Results from a Field Experiment.”](https://gup.ub.gu.se/file/208454) *Journal of Experimental Political Science* 7 (3): 199–208.

Esaiasson, Peter, Mikael Persson, Mikael Gilljam, and Torun Lindholm. 2019. [“Reconsidering the Role of Procedures for Decision Acceptance.”](bjps19.pdf) *British Journal of Political Science* 49 (1): 291–314.

Lindgren, Karl-Oskar, Sven Oskarsson, and Mikael Persson. 2019. [“Access to Education and Political Candidacy: Lessons from School Openings in Sweden.”](eer19.pdf) *Economics of Education Review* 69: 138–48.

Lindgren, Karl-Oskar, Sven Oskarsson, and Mikael Persson. 2019. [“Enhancing Electoral Equality: Can Education Compensate for Family Background Differences in Voting Participation?”](apsr19.pdf) *American Political Science Review* 113 (1): 108–22.

Persson, Mikael, and Johan Martinsson. 2018. [“Patrimonial Economic Voting and Asset Value–New Evidence from Taxation Register Data.”](bjps18.pdf) *British Journal of Political Science* 48 (3): 825–42.

Healy, Andrew J, Mikael Persson, and Erik Snowberg. 2017. [“Digging into the Pocketbook: Evidence on Economic Voting from Income Registry Data Matched to a Voter Survey.”](apsr17.pdf) *American Political Science Review* 111 (4): 771–85.

Esaiasson, Peter, Mikael Gilljam, and Mikael Persson. 2017. [“Responsiveness Beyond Policy Satisfaction: Does It Matter to Citizens?”](cps17.pdf) *Comparative Political Studies* 50 (6): 739–65.

Esaiasson, Peter, Mikael Gilljam, and Mikael Persson. 2017. “Political Support in the Wake of Policy Controversies.” In Myth and Reality of the Legitimacy Crisis. Explaining Trends and Cross-National Differences in Established Democracies. Oxford University Press.

Persson, Mikael, Karl-Oskar Lindgren, and Sven Oskarsson. 2016. [“How Does Education Affect Adolescents’ Political Development?”](eer16.pdf) *Economics of Education Review* 53: 182–93.

Bakker, Bert N, David Nicolas Hopmann, and Mikael Persson. 2015. [“Personality Traits and Party Identification over Time.”](ejpr15.pdf) *European Journal of Political Research* 54 (2): 197–215.

Persson, Mikael. 2015. [“Classroom Climate and Political Learning: Findings from a Swedish Panel Study and Comparative Data.”](pp15.pdf) *Political Psychology* 36 (5): 587–601.

Persson, Mikael. 2015. [“Education and Political Participation.”](bjps15.pdf) *British Journal of Political Science* 45 (3): 689–703.

Dahlberg, Stefan, and Mikael Persson. 2014. [“Different Surveys, Different Results? A Comparison of Two Surveys on the 2009 European Parliamentary Election.”](wep14.pdf) *West European Politics* 37 (1): 204–21.

Esaiasson, Peter, and Mikael Persson. 2014. [“Does Studying Political Science Affect Civic Attitudes?: A Panel Comparison of Students of Politics, Law, and Mass Communication.”](jpse14.pdf) *Journal of Political Science Education* 10 (4): 375–85.

Persson, Mikael. 2014. [“Does Survey Participation Increase Voter Turnout? Re-Examining the Hawthorne Effect in the Swedish National Election Studies.”](psrm14.pdf) *Political Science Research and Methods* 2 (2): 297.

Persson, Mikael. 2014. [“Social Network Position Mediates the Effect of Education on Active Political Party Membership.”](pp12.pdf) *Party Politics* 20 (5): 724–39.

Persson, Mikael. 2014. [“Testing the Relationship Between Education and Political Participation Using the 1970 British Cohort Study.”](pb14.pdf) *Political Behavior* 36 (4): 877–97.

Persson, Mikael, and Maria Solevid. 2014. [“Measuring Political Participation—Testing Social Desirability Bias in a Web-Survey Experiment.”](ijpor.pdf) *International Journal of Public Opinion Research* 26 (1): 98–112.

Persson, Mikael, Peter Esaiasson, and Mikael Gilljam. 2013. [“The Effects of Direct Voting and Deliberation on Legitimacy Beliefs: An Experimental Study of Small Group Decision-Making.”](epsr.pdf) *European Political Science Review* 5 (3): 381–99.

Persson, Mikael. 2013. [“Is the Effect of Education on Voter Turnout Absolute or Relative? A Multi-Level Analysis of 37 Countries.”](ijpor.pdf) *Journal of Elections, Public Opinion & Parties* 23 (2): 111–33.

Esaiasson, Peter, Mikael Gilljam, and Mikael Persson. 2012. [“Which Decision-Making Arrangements Generate the Strongest Legitimacy Beliefs? Evidence from a Randomised Field Experiment.”](ejpr12.pdf) *European Journal of Political Research* 51 (6): 785–808.

Gilljam, Mikael, Mikael Persson, and David Karlsson. 2012. [“Representatives’ Attitudes Toward Citizen Protests in Sweden: The Impact of Ideology, Parliamentary Position, and Experiences.”]() *Legislative Studies Quarterly* 37 (2): 251–68.

Persson, Mikael. 2012. [“Does Type of Education Affect Political Participation? Results from a Panel Survey of Swedish Adolescents.”]() *Scandinavian Political Studies* 35 (3): 198–221.

Persson, Mikael, and Henrik Oscarsson. 2010. [“Did the Egalitarian Reforms of the Swedish Educational System Equalise Levels of Democratic Citizenship?”](sps10.pdf) *Scandinavian Political Studies* 33 (2): 135–63.


